menu = tk.Menu(root)
file_menu = tk.Menu(menu, tearoff=0)
file_menu.add_command(label="New", command=entrer)
file_menu.add_command(label="Quitter", command=root.quit)
menu.add_cascade(label="Fichier", menu=file_menu)
root.config(menu=menu)
